name: CoinSystem
main: CoinSystem\Main
api: 5.0.0
version: 1.0
author: SemihAkin685

commands:
  coin:
    description: "Coinini görürsün."
    permission: pocketmine.group.user

  coingonder:
    description: "Oyuncuya coin gönderirsin."
    permission: pocketmine.group.user

  coinmarket:
    description: "CoinMarket menüsünü açar."
    permission: pocketmine.group.user

  coinayarla:
    description: "Oyuncunun coinini ayarlar."
    permission: coin.ayarla

permissions:
  coin.ayarla:
    description: Coin ayarlama yetkisi
    default: op